### ISSUE TITLE
List of working devices?

### ISSUE THREAD

**Issue by garengllc** [dannytsang/pyubibot#1]
This seems like it might be what I've been searching for.  I've been wanting to get some MS1 motion sensors and just talk to them offline directly from a Linux box.  It looks like the only "official" way to do it is via their Windows app, but I was hoping this might work for what I need.  Is there a list of the devices that should work for your library? TIA.

**Comment by dannytsang** [comment]
The code currently uses the official API so it will need an internet connection and won't work offline.

It's still early days and I haven't seen / tested it with a MS1 yet.

**Comment by dannytsang** [comment]
There doesn't seem to any documentation on the MS1 and APIs as of today. I am closing this request because without this, this package won't be able to support MS1.
