### ISSUE TITLE
setup.py "request>=2.28.0" should be "requests>=2.28.0"

### ISSUE THREAD

**Issue by daemondriver** [dannytsang/pyubibot#3]
setup.py causes an error:

No local packages or working download links found for request>=2.28.0
error: Could not find suitable distribution for Requirement.parse('request>=2.28.0')

Lines 22-23:

    install_requires=[
        "request>=2.28.0"

should be:

    install_requires=[
        "requests>=2.28.0"

Then it works fine:
Processing dependencies for pyubibot==0.0.4
Searching for requests==2.29.0
Best match: requests 2.29.0
Adding requests 2.29.0 to easy-install.pth file
<snipped for brevity>
Finished processing dependencies for pyubibot==0.0.4

**Comment by dannytsang** [comment]
Thanks @daemondriver
